# theme.toml

name = "Slender"
license = "MIT"
licenselink = "https://github.com/CrimsonRay/slender/blob/master/LICENSE.md"
description = "Minimalist theme for Hugo with base16 color schemes."
homepage = "https://crimsonray.github.io/slender/"
tags = ["hugo", "blog", "slender"]
features = ["blog"]
min_version = 0.14

[author]
  name = "CrimsonRay"
  homepage = "https://github.com/CrimsonRay/"

[original]
  name = ""
  homepage = ""
  repo = ""
